name: Mike Gillespie
favicon: null
layout_spectrum: 0.87027
typography_spectrum: 0.3163
title: Test driving AI web design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e97ab'
    - '#545359'
    - '#0c0b10'
    - '#f9af64'
    - '#b6521d'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
