name: Mike Gillespie
favicon: null
layout_spectrum: 0.54656
typography_spectrum: 0.60265
title: Test driving AI web design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#03080b'
    - '#2b2f32'
    - '#685c50'
    - '#4d463e'
    - '#9f8f81'
  brandStrength: 1
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
