name: Mike Gillespie
favicon: null
layout_spectrum: 0.59467
typography_spectrum: 0.92715
title: Test driving AI web design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e97ab'
    - '#545359'
    - '#0c0b10'
    - '#f9af64'
    - '#b6521d'
  brandStrength: 0.0625
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
